# Copyright Felix Ungman. All rights reserved.
# Licensed under GNU General Public License version 3 or later.

name: WebApp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: npm install
      run: cd webapp && npm install

    - name: build
      run: cd webapp && npm run build

    - name: test
      run: cd webapp && npm run test
